# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.discord_client_id: '%env(DISCORD_CLIENT_ID)%'
    app.discord_client_secret: '%env(DISCORD_CLIENT_SECRET)%'
    app.discord_webhook: '%env(DISCORD_WEBHOOK)%'
    app.discord_bot_token: '%env(DISCORD_BOT_TOKEN)%'
    app.discord_server_id: '%env(DISCORD_SERVER_ID)%'
    app.discord_role_id: '%env(DISCORD_ROLE_ID)%'
    app.discord_whitelist_role_id: '%env(DISCORD_WHITELIST_ROLE_ID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $discordWebhook: '%app.discord_webhook%'
            string $discordBotToken: '%app.discord_bot_token%'
            string $discordServerId: '%app.discord_server_id%'
            string $discordRoleId: '%app.discord_role_id%'
            string $discordWhitelistRoleId: '%app.discord_whitelist_role_id%'
            string $kernelEnvironment: '%kernel.environment%'
            string $uploadDirectory: '%upload_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\DiscordUserProvider:
        arguments:
            $discordClientId: '%app.discord_client_id%'
            $discordClientSecret: '%app.discord_client_secret%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
